[package]
name = "wrach-bevy"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
# Remove "shader_format_spirv" feature when this issue is fixed:
#   https://github.com/AnthonyTornetta/bevy_easy_compute/issues/7
bevy_easy_compute = { git = "https://github.com/AnthonyTornetta/bevy_easy_compute", features = ["shader_format_spirv"] }
rand = "0.8.5"

[lints]
workspace = true
