[package]
name = "wrach-physics-shaders"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
# TODO: Add to workspace root and pin to a hash
spirv-std = { git = "https://github.com/EmbarkStudios/rust-gpu" }

[lints]
workspace = true

