[package]
name = "wrach-cpu-gpu-shared"
version = "0.0.0"
edition = "2021"

[dependencies]
spirv-std = { workspace = true }

[target.'cfg(not(target_arch = "spirv"))'.dependencies]
bevy = { workspace = true }

[lints]
workspace = true

