[package]
name = "wrach-physics-example"
version = "0.0.0"
authors = []
edition = "2018"

[dependencies]
wrach-physics-shaders = { path = "../../shaders/physics" }
wrach-renderer-shader = { path = "../../shaders/renderer" }
wrach-wgpu = { path = "../../runners/wgpu" }

